# Generated by Django 3.1.2 on 2020-11-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokes', '0002_auto_20201116_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='Image',
            field=models.ImageField(upload_to='myimages'),
        ),
    ]
