# Generated by Django 3.1.2 on 2020-11-30 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokes', '0006_auto_20201129_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='Brands_Website',
            field=models.CharField(default='#', max_length=100),
        ),
    ]
