# Generated by Django 5.0.7 on 2024-07-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Job_Title', models.CharField(max_length=20)),
                ('Phone_Number', models.CharField(default='None', max_length=20)),
                ('Email', models.CharField(default='None', max_length=50)),
                ('Resume', models.FileField(upload_to='resumes')),
                ('Submitted', models.DateTimeField(auto_now_add=True)),
                ('Viewed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='myimages')),
                ('Brands_Website', models.CharField(default='#', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=60)),
                ('Image', models.ImageField(upload_to='myimages')),
                ('Start_Time', models.CharField(max_length=15)),
                ('End_time', models.CharField(max_length=15)),
                ('Date', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=70)),
                ('Link_URL', models.CharField(default='https://stokesdistributing.herokuapp.com/', max_length=500)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Phone_Number', models.CharField(default='None', max_length=20)),
                ('Email', models.CharField(default='None', max_length=50)),
                ('Subject', models.CharField(max_length=50)),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='New_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=50, null=True)),
                ('Image', models.ImageField(upload_to='myimages')),
            ],
        ),
    ]
