# Generated by Django 5.0.7 on 2024-07-30 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplcationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binary_data', models.BinaryField(blank=True, editable=True, null=True)),
                ('content_type', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='NewProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('binary_data', models.BinaryField(blank=True, editable=True, null=True)),
                ('content_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='New_Product',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='Job_Title',
            new_name='job_title',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='Phone_Number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='Resume',
            new_name='resume',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='Submitted',
            new_name='submitted',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='Viewed',
            new_name='viewed',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='Brands_Website',
            new_name='brands_website',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='End_time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Link_URL',
            new_name='link_url',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Start_Time',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='Message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='Phone_Number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='Subject',
            new_name='subject',
        ),
        migrations.AddField(
            model_name='applcationfile',
            name='application_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stokes.application'),
        ),
    ]
