# Generated by Django 5.0.7 on 2024-07-30 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokes', '0002_applcationfile_newproduct_delete_new_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stokes.event')),
                ('binary_data', models.BinaryField(blank=True, editable=True, null=True)),
                ('content_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='applcationfile',
            name='application_id',
        ),
        migrations.RemoveField(
            model_name='applcationfile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='application',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.RemoveField(
            model_name='newproduct',
            name='binary_data',
        ),
        migrations.AddField(
            model_name='applcationfile',
            name='application',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stokes.application'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='content_type',
            field=models.CharField(default='t', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newproduct',
            name='image',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='job_title',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='link_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='newproduct',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
