# Generated by Django 5.0.7 on 2024-07-31 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokes', '0003_eventimage_remove_applcationfile_application_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='filename',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='eventimage',
            name='filename',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='newproduct',
            name='filename',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='applcationfile',
            name='file_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brands_website',
            field=models.CharField(default='', max_length=100),
        ),
    ]
