# Generated by Django 5.0.7 on 2024-07-31 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokes', '0004_brand_filename_eventimage_filename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applcationfile',
            name='file_name',
        ),
        migrations.AddField(
            model_name='applcationfile',
            name='filename',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
