# Generated by Django 5.0.7 on 2024-07-31 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stokes', '0005_remove_applcationfile_file_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplcationFile',
            new_name='ApplicationFile',
        ),
    ]
